server:
  port: 8080

spring:
  application:
    name: bank-mcp-client
  ai:
    mcp:
      client:
        type: SYNC
        streamable-http:
          connections:
            bank-server:
              url: http://localhost:8081
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:1.5b

logging:
  level:
    com.hydroyura.mcp.client: DEBUG
